[package]
name = "data-patterns"
version = "0.1.0"
edition = "2024"


[dependencies]
tokio = { version = "1.38", features = ["full"] }

sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "macros", "migrate"] }

redis = { version = "0.27", features = ["tokio-comp", "connection-manager"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
dotenvy = "0.15"
axum = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1", features = ["v4"] }
reqwest = { version = "0.12", features = ["json"] }
